sudo: required
services: 
    - docker

before-install:
    - docker build -t ajraj27/docker-react -f Dockerfile.dev .

script:
    -  docker run -e CI=true ajraj27/docker-react npm run test 
    
deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-700609510333"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECURE_KEY

